spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 01764a11a4563e2cb386973fbf64ef394a0743b7f0b083af985674e545feee97
    url: postgres://vpeleizonmgtfo:01764a11a4563e2cb386973fbf64ef394a0743b7f0b083af985674e545feee97@ec2-44-194-4-127.compute-1.amazonaws.com:5432/d18b4gea3issqb
    username: vpeleizonmgtfo
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        formatsql: true
    hibernate:
      ddl-auto: update
    show-sql: true
